version: '3.1'
services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
        - database

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
        - pgadmin-data:/var/lib/pgadmin
    networks:
      - database
    ports:
      - 5050:80
    depends_on:
      - db
    restart: unless-stopped
    links:
      - "db:pgsql-server"


volumes:
  data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  database:
    driver: bridge